server:
  #allowedOrigins: ["http://localhost:8888","http://127.0.0.1:8888","http://localhost:9993"] 
  #allowedOrigins: ["*"]  # universal, but wrong. 
  allowedOrigins: ["<replace_me_on_real_origin>","http://localhost:9993","http://127.0.0.1:9993"]  # Use it as sed placeholder 
  #allowedOrigins: ["http://localhost:9993","http://127.0.0.1:9993"]  
kafka:
  schemaRegistry:
    enabled: true
    urls: ["http://karapace-registry:8081"]
##  username: user_name
##  password: user_password

## https://docs.redpanda.com/docs/manage/console/kafka-connect/

connect:
  enabled: true
  clusters:
    - name: debezium # Required field, will be used as identifier in the frontend
      url: http://debezium:8083/
      tls:
        enabled: false # Trusted certs are still allowed by default